### PR TITLE
Usecase should have access to req.user inside ctx

### PR DESCRIPTION
**Pull request by vitorgamer58**
Feature https://github.com/herbsjs/herbs2rest/issues/41

## Proposed Changes

1. Added injection in the defaultController function so that req.user data can be accessed within usecase steps through ctx.di

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by vitorgamer58** [comment]
Is working
Usecase working

**Review by jhomarolo — CHANGES_REQUESTED** [review]
Good PR @vitorgamer58, but I think the doc about this is missing

**Comment by vitorgamer58** [comment]
> Good PR @vitorgamer58, but I think the doc about this is missing

I'll work on this.

**Comment by vitorgamer58** [comment]
@jhomarolo I'm not sure if I'm satisfied with the documentation of my feature, I believe the documentation needs a little more context about the req.user, maybe with some middleware example from express.

**Comment by vitorgamer58** [comment]
I agree

**Pull request closed without merging**
